
/// <reference types="cypress" />

describe('example to-do app', () => {
  beforeEach(() => {
  })

  it("", () => {

  })

  it("check non-end spot leap frog", () => {

  })

  it("new round starts when oxygen runs out, and treasures are dropped", () => {

  })

  it("new round starts when no players left", () => {
    cy.visit('localhost:3000/deepseadiving')
    cy.get("#resetTests").click()
    cy.wait(100)
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof2").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof2").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof2").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof2").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#turnAround").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#turnAround").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#turnAround").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#turnAround").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.contains("00000000000000000000000000000000")
    cy.contains("Oxygen Counter 25")
  })

  // it("movement with one treasure is one less", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#takeTreasure").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#turnAround").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.contains("10000023400000000000000000000000")
  // })

  // it("player leaves board when they return to the start before oxygen runs out", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof5").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#turnAround").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.contains("00000023400000000000000000000000")
  // })

  // it("bounce off back", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.contains("00000000000000000000000000004312")
  // })

  // it("check leap frog second player same as first", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.contains("00000120000000000000000000000000")
  // })
})
