
/// <reference types="cypress" />

describe('example to-do app', () => {
  beforeEach(() => {
  })

  it("", () => {

  })

  it("bring back piled treasure, saved normally", () => {

  })

  it("win game calculation points", () => {

  })

  it("pickup piled treasure with more than 1 treasure, only makes movement 1 slower", () => {
    cy.visit('localhost:3000/deepseadiving')
    cy.get("#resetTests").click()
    cy.wait(100)
    cy.get("#oxygenArea").clear().type("3")
    cy.get("#oxygenAreaButton").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#takeTreasure").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#takeTreasure").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#takeTreasure").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#takeTreasure").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof2").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof2").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof2").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof6").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof2").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof2").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.get("#setCurrentPlayer").click()
    cy.get("#continue").click()
    cy.wait(100)
    cy.get("#spoof2").click()
    cy.wait(100)
    cy.get("#noAction").click()
    cy.wait(100)
    cy.contains("00000000000000000000000000000")
    cy.contains("[1,1,1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,[2,1,2],[2]")
    cy.contains("Oxygen Counter 25")
    cy.contains("Remaining Rounds (Excluding Current Round) 1")
  })

  // it("more than 4 treasures dropped, pile order is correct", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#oxygenArea").clear().type("3")
  //   cy.get("#oxygenAreaButton").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#takeTreasure").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#takeTreasure").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#takeTreasure").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#takeTreasure").click()
  //   cy.wait(100)
  //   cy.contains("00000000000000000000000000000")
  //   cy.contains("[1,1,1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,[2,1,2],[2]")
  //   cy.contains("Oxygen Counter 25")
  //   cy.contains("Remaining Rounds (Excluding Current Round) 1")
  // })

  // it("multiple players lose held treasures, pile order is correct", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#oxygenArea").clear().type("1")
  //   cy.get("#oxygenAreaButton").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#takeTreasure").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#takeTreasure").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.contains("0000000000000000000000000000000")
  //   cy.contains("[1,1,1,1,1,1,1,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,[2,1]]")
  //   cy.contains("Oxygen Counter 25")
  //   cy.contains("Remaining Rounds (Excluding Current Round) 1")
  // })

  // it("new round starts when oxygen runs out, and treasures are dropped", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#oxygenArea").clear().type("1")
  //   cy.get("#oxygenAreaButton").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof2").click()
  //   cy.wait(100)
  //   cy.get("#takeTreasure").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof2").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof2").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof2").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#setCurrentPlayer").click()
  //   cy.contains("00000000000000000000000000000000")
  //   cy.contains("[1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,[1]]")
  //   cy.contains("Oxygen Counter 25")
  //   cy.contains("Remaining Rounds (Excluding Current Round) 1")
  // })

  // it("new round starts when no players left", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof2").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof2").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof2").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof2").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#turnAround").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#turnAround").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#turnAround").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#turnAround").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.contains("00000000000000000000000000000000")
  //   cy.contains("Oxygen Counter 25")
  //   cy.contains("Remaining Rounds (Excluding Current Round) 1")
  // })

  // it("movement with one treasure is one less", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#takeTreasure").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#turnAround").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.contains("10000023400000000000000000000000")
  // })

  // it("player leaves board when they return to the start before oxygen runs out", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof5").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#turnAround").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.contains("00000023400000000000000000000000")
  // })

  // it("bounce off back", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.contains("00000000000000000000000000004312")
  // })

  // it("check leap frog second player same as first", () => {
  //   cy.visit('localhost:3000/deepseadiving')
  //   cy.get("#resetTests").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.wait(100)
  //   cy.get("#noAction").click()
  //   cy.wait(100)
  //   cy.get("#continue").click()
  //   cy.wait(100)
  //   cy.get("#spoof6").click()
  //   cy.contains("00000120000000000000000000000000")
  // })
})
